# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']   # Docker Compose service name + internal port

  # Optional: scrape the tei-embeddings model container if it exposes metrics (not by default)
  # - job_name: 'tei-embeddings'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['tei-embeddings:80']
